log_level: DEBUG
address: ":50051"
token_ttl: 15m
refresh_token_ttl: 720h
db_address: "postgres://postgres:password@auth-postgres:5432/authdb?sslmode=disable"
env: local
jwt_issuer: "auth-service"
jwt_secret: "super-secret-key"